version: 2.1

orbs:
  docker: circleci/docker@1.7.0

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    working_directory: ~/frontend
    steps:
      - docker/build:
          image: circleci/node:13.8.0 
          lint-dockerfile: false 
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            Build front-end
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
             # Your code here
             exit 1
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend